/**
 * Seed courts data to Firestore
 * Run: npx tsx scripts/seed-courts.ts
 * 
 * Deletes all existing courts first, then creates fresh ones.
 */

import { initFirestore, COLLECTIONS } from '../src/db/firestore.js';
import { v4 as uuidv4 } from 'uuid';

const courts = [
  {
    name: "Ada Mckenzie Park",
    address: "185 South Park Road",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8402,
    longitude: -79.3838,
  },
  {
    name: "Armadale Park",
    address: "2401 Denison Street",
    city: "Markham",
    location: "Armadale Tennis Club",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "CLOSED",
    latitude: 43.8408,
    longitude: -79.2808,
  },
  {
    name: "Bayview Glen Park",
    address: "48 Limcombe Drive",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8107,
    longitude: -79.3904,
  },
  {
    name: "Bayview Reservoir",
    address: "8079 Bayview Avenue",
    city: "Markham",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8285,
    longitude: -79.4033,
  },
  {
    name: "Berzcy Park North",
    address: "447 The Bridle Walk",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8933,
    longitude: -79.3069,
  },
  {
    name: "Berzcy Park South",
    address: "432 Wilfred Murison Avenue",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8900,
    longitude: -79.2966,
  },
  {
    name: "Blowden Davies Park",
    address: "335 Donald Cousens Parkway",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8906,
    longitude: -79.2127,
  },
  {
    name: "Boxgrove Community Park",
    address: "346 Boxgrove Bypass",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "Saturday and Sunday 12 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.8604,
    longitude: -79.2248,
  },
  {
    name: "Carlton Park",
    address: "101 Carlton Road",
    city: "Markham",
    location: "Unionville Tennis Club",
    totalCourts: 9,
    hasLights: true,
    hours: "Courts 1,2,3 & 4: Tuesdays 12pm - 4pm, Courts 1 & 2: Saturdays 6pm - 10pm",
    status: "CLOSED",
    latitude: 43.8751,
    longitude: -79.2940,
  },
  {
    name: "Duncan Park",
    address: "265 Bayview Fairways Drive",
    city: "Markham",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8194,
    longitude: -79.3840,
  },
  {
    name: "Frisby Park",
    address: "15 Murison Drive",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8915,
    longitude: -79.3750,
  },
  {
    name: "Cornell Community Park",
    address: "371 Cornell Centre Blvd.",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8912,
    longitude: -79.2251,
  },
  {
    name: "German Mills Park",
    address: "15 Simonston Boulevard",
    city: "Markham",
    location: "German Mills Tennis Club",
    totalCourts: 4,
    hasLights: true,
    hours: "Courts 1, 2: Fridays 6 PM to 8 PM, Saturdays 2 PM to 4 PM, Sundays 4 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.8180,
    longitude: -79.3680,
  },
  {
    name: "Grandview Park",
    address: "135 Doncastor Avenue",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8021,
    longitude: -79.4196,
  },
  {
    name: "Henry White Park",
    address: "135 Moss Creek Boulevard",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7AM to Dark",
    status: "CLOSED",
    latitude: 43.8789,
    longitude: -79.3698,
  },
  {
    name: "Highgate Park",
    address: "37 Highgate Drive",
    city: "Markham",
    location: "Highgate Tennis Club",
    totalCourts: 3,
    hasLights: true,
    hours: "Sundays 9 PM to 11 PM, Mondays 9 PM to 11 PM, Wednesdays 7 AM to 9 AM",
    status: "CLOSED",
    latitude: 43.8285,
    longitude: -79.3161,
  },
  {
    name: "Johnsview Park",
    address: "27 Porterfield Crescent",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8172,
    longitude: -79.3983,
  },
  {
    name: "Laura & Alf Weaver Park",
    address: "190 Williamson Road",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8984,
    longitude: -79.2564,
  },
  {
    name: "Morgan Park",
    address: "11 Parkway Avenue",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8817,
    longitude: -79.2589,
  },
  {
    name: "Pomona Mills Park",
    address: "200 John Street",
    city: "Markham",
    location: "Pomona Valley Tennis Club",
    totalCourts: 6,
    hasLights: true,
    hours: "Courts 5, 6: Saturday and Sunday 12 PM to 6 PM",
    status: "CLOSED",
    latitude: 43.8183,
    longitude: -79.4037,
  },
  {
    name: "Roy Ramer Park",
    address: "11 James Parrot Ave.",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7989,
    longitude: -79.3234,
  },
  {
    name: "Reesor Park",
    address: "73 Wootten Way North",
    city: "Markham",
    location: "Markham Tennis Club",
    totalCourts: 6,
    hasLights: true,
    hours: "Courts 4,5 and 6: Saturday & Sunday 3 PM to 7 PM",
    status: "CLOSED",
    latitude: 43.8876,
    longitude: -79.2455,
  },
  {
    name: "Robinson Park",
    address: "46 Robinson Street",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8738,
    longitude: -79.2734,
  },
  {
    name: "Schoolhouse Park",
    address: "7651 Ninth Line",
    city: "Markham",
    location: "Boxgrove Tennis Club",
    totalCourts: 2,
    hasLights: true,
    hours: "Saturday and Sunday 12 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.8565,
    longitude: -79.2291,
  },
  {
    name: "South Unionville Park",
    address: "514 Caboto Trail",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8547,
    longitude: -79.2933,
  },
  {
    name: "Toogood Park",
    address: "58 Sciberras Road",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8617,
    longitude: -79.3177,
  },
  {
    name: "Wismer Park",
    address: "980 Bur Oak Avenue",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8984,
    longitude: -79.2765,
  },
  {
    name: "Warden View Park",
    address: "30 Rouge Valley Drive",
    city: "Markham",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8500,
    longitude: -79.3301,
  },
  // Toronto courts
  {
    name: "Albion Gardens Park",
    address: "Albion Gardens Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7415,
    longitude: -79.6254,
  },
  {
    name: "Amesbury Park",
    address: "Amesbury Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6783,
    longitude: -79.4468,
  },
  {
    name: "Ancaster Park",
    address: "Ancaster Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6886,
    longitude: -79.3186,
  },
  {
    name: "Angela James Arena & Tennis Courts",
    address: "Angela James Arena & Tennis Courts",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7866,
    longitude: -79.2826,
  },
  {
    name: "Antibes Community Centre",
    address: "Antibes Community Centre",
    city: "Toronto",
    location: "Public",
    totalCourts: 1,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7280,
    longitude: -79.5587,
  },
  {
    name: "Baycrest Park",
    address: "Baycrest Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7627,
    longitude: -79.4109,
  },
  {
    name: "Bayview Village Park",
    address: "Bayview Village Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7693,
    longitude: -79.3843,
  },
  {
    name: "Beaumonde Heights Park",
    address: "Beaumonde Heights Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7512,
    longitude: -79.5939,
  },
  {
    name: "Bestview Park",
    address: "Bestview Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7058,
    longitude: -79.5161,
  },
  {
    name: "Birch Park",
    address: "Birch Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6891,
    longitude: -79.3361,
  },
  {
    name: "Birchmount Park",
    address: "Birchmount Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6528,
    longitude: -79.5433,
  },
  {
    name: "Bloordale Park South",
    address: "Bloordale Park South",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6657,
    longitude: -79.4581,
  },
  {
    name: "Buttonwood Park",
    address: "Buttonwood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6394,
    longitude: -79.5196,
  },
  {
    name: "Cedarvale Park",
    address: "Cedarvale Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6993,
    longitude: -79.4082,
  },
  {
    name: "Chalkfarm Park",
    address: "Chalkfarm Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7069,
    longitude: -79.4521,
  },
  {
    name: "Champlain Parkette",
    address: "Champlain Parkette",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6896,
    longitude: -79.4928,
  },
  {
    name: "Clairlea Park",
    address: "Clairlea Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7108,
    longitude: -79.2819,
  },
  {
    name: "Cliffwood Park",
    address: "Cliffwood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6912,
    longitude: -79.3524,
  },
  {
    name: "Cloverdale Park",
    address: "Cloverdale Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6635,
    longitude: -79.4528,
  },
  {
    name: "Coleman Park",
    address: "Coleman Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6795,
    longitude: -79.3517,
  },
  {
    name: "Cummer Park",
    address: "Cummer Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7871,
    longitude: -79.3702,
  },
  {
    name: "Dovercourt Park",
    address: "Dovercourt Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6688,
    longitude: -79.4319,
  },
  {
    name: "Earlscourt Park",
    address: "Earlscourt Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 1,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6989,
    longitude: -79.4357,
  },
  {
    name: "East Mall Park",
    address: "East Mall Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6205,
    longitude: -79.5463,
  },
  {
    name: "Eglinton Flats",
    address: "Eglinton Flats",
    city: "Toronto",
    location: "Public",
    totalCourts: 13,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7103,
    longitude: -79.4651,
  },
  {
    name: "Eglinton Park",
    address: "Eglinton Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6919,
    longitude: -79.4534,
  },
  {
    name: "Elie Wiesel Park",
    address: "Elie Wiesel Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7884,
    longitude: -79.3617,
  },
  {
    name: "Fairmount Park",
    address: "Fairmount Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6628,
    longitude: -79.3241,
  },
  {
    name: "Fenside Park",
    address: "Fenside Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7173,
    longitude: -79.3386,
  },
  {
    name: "Firgrove Park",
    address: "Firgrove Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6501,
    longitude: -79.5484,
  },
  {
    name: "Flagstaff Park",
    address: "Flagstaff Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6824,
    longitude: -79.5307,
  },
  {
    name: "Gihon Spring Park",
    address: "Gihon Spring Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7265,
    longitude: -79.3671,
  },
  {
    name: "Glen Park",
    address: "Glen Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7098,
    longitude: -79.4407,
  },
  {
    name: "Glendora Park",
    address: "Glendora Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7027,
    longitude: -79.5253,
  },
  {
    name: "Goulding Park",
    address: "Goulding Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7563,
    longitude: -79.4497,
  },
  {
    name: "Gracedale Park",
    address: "Gracedale Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7438,
    longitude: -79.4556,
  },
  {
    name: "Grandravine Park",
    address: "Grandravine Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7487,
    longitude: -79.5372,
  },
  {
    name: "Graydon Hall Park",
    address: "Graydon Hall Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7416,
    longitude: -79.3587,
  },
  {
    name: "Gwendolen Park",
    address: "Gwendolen Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 1,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6845,
    longitude: -79.3891,
  },
  {
    name: "Hendon Park",
    address: "Hendon Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7598,
    longitude: -79.4018,
  },
  {
    name: "High Park",
    address: "High Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 7,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6595,
    longitude: -79.4646,
  },
  {
    name: "Howard Talbot Park",
    address: "Howard Talbot Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6926,
    longitude: -79.5098,
  },
  {
    name: "Hullmar Park",
    address: "Hullmar Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7365,
    longitude: -79.6067,
  },
  {
    name: "Humber Valley Park",
    address: "Humber Valley Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6378,
    longitude: -79.5486,
  },
  {
    name: "Indian Line Park",
    address: "Indian Line Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6718,
    longitude: -79.5689,
  },
  {
    name: "Irving W. Chapley Park",
    address: "Irving W. Chapley Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7461,
    longitude: -79.4578,
  },
  {
    name: "Jeff Healey Park",
    address: "Jeff Healey Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6547,
    longitude: -79.5834,
  },
  {
    name: "Jimmie Simpson Park",
    address: "Jimmie Simpson Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6645,
    longitude: -79.3397,
  },
  {
    name: "Jonathan Ashbridge Park",
    address: "Jonathan Ashbridge Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6698,
    longitude: -79.3124,
  },
  {
    name: "Kingsview Park",
    address: "Kingsview Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7357,
    longitude: -79.4816,
  },
  {
    name: "Kirkwood Park",
    address: "Kirkwood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6893,
    longitude: -79.4751,
  },
  {
    name: "Laburnham Park",
    address: "Laburnham Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7415,
    longitude: -79.5043,
  },
  {
    name: "Lakeshore Boulevard Parklands",
    address: "Lakeshore Boulevard Parklands",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6371,
    longitude: -79.4618,
  },
  {
    name: "Lambton - Kingsway Park",
    address: "Lambton - Kingsway Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6366,
    longitude: -79.5147,
  },
  {
    name: "Lanyard Park",
    address: "Lanyard Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7316,
    longitude: -79.5221,
  },
  {
    name: "Malvern Park",
    address: "Malvern Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7185,
    longitude: -79.2139,
  },
  {
    name: "Manchester Park",
    address: "Manchester Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6923,
    longitude: -79.5362,
  },
  {
    name: "Maple Leaf Park",
    address: "Maple Leaf Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6721,
    longitude: -79.5528,
  },
  {
    name: "Martingrove Gardens Park",
    address: "Martingrove Gardens Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6984,
    longitude: -79.5842,
  },
  {
    name: "McDairmid Woods Park",
    address: "McDairmid Woods Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7382,
    longitude: -79.4876,
  },
  {
    name: "McGregor Park",
    address: "McGregor Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6794,
    longitude: -79.4318,
  },
  {
    name: "Mcnicoll Park",
    address: "Mcnicoll Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7918,
    longitude: -79.3547,
  },
  {
    name: "Michael Mostyn Balmoral Park",
    address: "Michael Mostyn Balmoral Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6539,
    longitude: -79.5691,
  },
  {
    name: "Mill Valley Park",
    address: "Mill Valley Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7419,
    longitude: -79.4657,
  },
  {
    name: "Millwood Park",
    address: "Millwood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7284,
    longitude: -79.3579,
  },
  {
    name: "Moore Park - Nrth York",
    address: "Moore Park - Nrth York",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7281,
    longitude: -79.3768,
  },
  {
    name: "Moss Park",
    address: "Moss Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 1,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6549,
    longitude: -79.3681,
  },
  {
    name: "Nrth Park",
    address: "Nrth Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7129,
    longitude: -79.4928,
  },
  {
    name: "Nrwood Park",
    address: "Nrwood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 5,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7234,
    longitude: -79.4339,
  },
  {
    name: "Oriole Park - Toronto",
    address: "Oriole Park - Toronto",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7716,
    longitude: -79.4139,
  },
  {
    name: "Ourland Park",
    address: "Ourland Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6428,
    longitude: -79.4835,
  },
  {
    name: "Park Lawn Park",
    address: "Park Lawn Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6327,
    longitude: -79.4846,
  },
  {
    name: "Pelmo Park",
    address: "Pelmo Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6918,
    longitude: -79.5257,
  },
  {
    name: "Pine Point Park",
    address: "Pine Point Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7216,
    longitude: -79.5176,
  },
  {
    name: "Prairie Drive Park",
    address: "Prairie Drive Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7439,
    longitude: -79.4871,
  },
  {
    name: "Prince of Wales Park",
    address: "Prince of Wales Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7647,
    longitude: -79.5028,
  },
  {
    name: "Princess Anne Park",
    address: "Princess Anne Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7291,
    longitude: -79.5123,
  },
  {
    name: "Queensway Park",
    address: "Queensway Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6491,
    longitude: -79.4623,
  },
  {
    name: "Ramsden Park",
    address: "Ramsden Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 12,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6812,
    longitude: -79.4019,
  },
  {
    name: "Riverdale Park East",
    address: "Riverdale Park East",
    city: "Toronto",
    location: "Public",
    totalCourts: 7,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6791,
    longitude: -79.3538,
  },
  {
    name: "Rockford Park",
    address: "Rockford Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7461,
    longitude: -79.4712,
  },
  {
    name: "Rotary Peace Park",
    address: "Rotary Peace Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7612,
    longitude: -79.4187,
  },
  {
    name: "Royal Crest Park",
    address: "Royal Crest Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7234,
    longitude: -79.5467,
  },
  {
    name: "Roywood Park",
    address: "Roywood Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7348,
    longitude: -79.4231,
  },
  {
    name: "Ruddington Park",
    address: "Ruddington Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7281,
    longitude: -79.4519,
  },
  {
    name: "Runnymede Park",
    address: "Runnymede Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6729,
    longitude: -79.4712,
  },
  {
    name: "Sentinel Park",
    address: "Sentinel Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7549,
    longitude: -79.4056,
  },
  {
    name: "Shawnee Park",
    address: "Shawnee Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7158,
    longitude: -79.5367,
  },
  {
    name: "Sir Adam Beck Park",
    address: "Sir Adam Beck Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6923,
    longitude: -79.5218,
  },
  {
    name: "Sorauren Avenue Park",
    address: "Sorauren Avenue Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6612,
    longitude: -79.4218,
  },
  {
    name: "Stanley Greene Park",
    address: "Stanley Greene Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7183,
    longitude: -79.4891,
  },
  {
    name: "Stanley Park",
    address: "Stanley Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6756,
    longitude: -79.3421,
  },
  {
    name: "Stanley Park South - Toronto",
    address: "Stanley Park South - Toronto",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6719,
    longitude: -79.3398,
  },
  {
    name: "Strathburn Park",
    address: "Strathburn Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7368,
    longitude: -79.5321,
  },
  {
    name: "Summerlea Park",
    address: "Summerlea Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6412,
    longitude: -79.5834,
  },
  {
    name: "Sunnydale Acres Park",
    address: "Sunnydale Acres Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7289,
    longitude: -79.3891,
  },
  {
    name: "Sunnylea Park",
    address: "Sunnylea Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6927,
    longitude: -79.4987,
  },
  {
    name: "Sweeney Park",
    address: "Sweeney Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7218,
    longitude: -79.4612,
  },
  {
    name: "Symington Avenue Playground",
    address: "Symington Avenue Playground",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6387,
    longitude: -79.4289,
  },
  {
    name: "Topham Park",
    address: "Topham Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7261,
    longitude: -79.3543,
  },
  {
    name: "Trinity Bellwoods Park",
    address: "Trinity Bellwoods Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 8,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6651,
    longitude: -79.4223,
  },
  {
    name: "Wedgewood Park - Etobicoke",
    address: "Wedgewood Park - Etobicoke",
    city: "Toronto",
    location: "Public",
    totalCourts: 1,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6718,
    longitude: -79.5678,
  },
  {
    name: "Wedgewood Park - Nrth York",
    address: "Wedgewood Park - Nrth York",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7412,
    longitude: -79.4617,
  },
  {
    name: "Westgrove Park",
    address: "Westgrove Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6879,
    longitude: -79.5432,
  },
  {
    name: "Westmount Park",
    address: "Westmount Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6987,
    longitude: -79.5189,
  },
  {
    name: "Westway Park",
    address: "Westway Park",
    city: "Toronto",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.7289,
    longitude: -79.5367,
  },
  {
    name: "Withrow Park and Clubhouse",
    address: "Withrow Park and Clubhouse",
    city: "Toronto",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.6798,
    longitude: -79.3521,
  },
  // Richmond Hill courts (with lights)
  {
    name: "Bayview Hill Park",
    address: "Spadina Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 6,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8689,
    longitude: -79.4009,
  },
  {
    name: "Brickworks Park",
    address: "Wildwood Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9552,
    longitude: -79.4372,
  },
  {
    name: "Crosby Park",
    address: "Crosby Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8838,
    longitude: -79.4240,
  },
  {
    name: "David Hamilton Park",
    address: "Valleymede Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8457,
    longitude: -79.3954,
  },
  {
    name: "French Royalist Park",
    address: "Rollinghill Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9096,
    longitude: -79.4569,
  },
  {
    name: "Grovewood Park",
    address: "Grovewood St, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9357,
    longitude: -79.4709,
  },
  {
    name: "Headwaters Community Park",
    address: "Redstone Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8867,
    longitude: -79.4121,
  },
  {
    name: "Morgan Boyle Park",
    address: "Pearson Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8424,
    longitude: -79.4373,
  },
  {
    name: "Mount Pleasant Park",
    address: "Harding Blvd West, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8667,
    longitude: -79.4424,
  },
  {
    name: "Newberry Park",
    address: "Bernard Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8998,
    longitude: -79.4347,
  },
  {
    name: "Silver Stream Park",
    address: "Shirley Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8906,
    longitude: -79.4109,
  },
  {
    name: "Stavert Park",
    address: "Regent St, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8808,
    longitude: -79.4560,
  },
  {
    name: "Tannery Park",
    address: "Castle Rock Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8501,
    longitude: -79.4526,
  },
  {
    name: "Town Park",
    address: "Church St South, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8652,
    longitude: -79.4336,
  },
  // Richmond Hill courts (no lights)
  {
    name: "Fontainbleu Park",
    address: "Worthington Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9561,
    longitude: -79.4458,
  },
  {
    name: "Hunter's Point Wildlife Park",
    address: "Hunter's Point Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8363,
    longitude: -79.4413,
  },
  {
    name: "Larrat Lea Park",
    address: "Shaftsbury Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8935,
    longitude: -79.4557,
  },
  {
    name: "MacLeod's Landing Park",
    address: "Shirrick Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9240,
    longitude: -79.4513,
  },
  {
    name: "Oak Ridges Lions Park",
    address: "Red Cardinal Trail, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 1,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9579,
    longitude: -79.4812,
  },
  {
    name: "Ozark Park",
    address: "Old Colony Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9387,
    longitude: -79.4412,
  },
  {
    name: "Pine Farm Park",
    address: "Ashfield Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 1,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9493,
    longitude: -79.4521,
  },
  {
    name: "Rocking Horse Ranch Park",
    address: "Hunting Ridges Drive, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9169,
    longitude: -79.4328,
  },
  {
    name: "Russell Farm Park",
    address: "Bantry Ave, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 4,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8457,
    longitude: -79.4236,
  },
  {
    name: "Russell Tilt Park",
    address: "Blackforest Dr, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9545,
    longitude: -79.4589,
  },
  {
    name: "William Harrison Park",
    address: "Colesbrook Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.9016,
    longitude: -79.4600,
  },
  {
    name: "Willow Grove Park",
    address: "Frank Endean Rd, Richmond Hill",
    city: "Richmond Hill",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "",
    status: "AVAILABLE",
    latitude: 43.8839,
    longitude: -79.4119,
  },
];

function generateCourtId(): string {
  return uuidv4();
}

async function seedCourts() {
  console.log('Initializing Firestore...');
  const db = initFirestore();
  
  // Delete all existing courts first
  console.log('Deleting existing courts...');
  const snapshot = await db.collection(COLLECTIONS.COURTS).get();
  const deletePromises = snapshot.docs.map(doc => doc.ref.delete());
  await Promise.all(deletePromises);
  console.log(`Deleted ${snapshot.size} existing courts`);
  
  console.log(`Seeding ${courts.length} courts...`);
  
  // Now create all courts fresh
  for (const court of courts) {
    const courtId = generateCourtId();
    const docRef = db.collection(COLLECTIONS.COURTS).doc(courtId);
    
    await docRef.set({
      ...court,
      courtType: "tennis",
      surface: "hard",
      isFree: court.location === "Public",
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }
  
  console.log(`Successfully seeded ${courts.length} courts to Firestore!`);
}

seedCourts().catch(console.error);