/**
 * Seed courts data to Firestore
 * Run: npx tsx scripts/seed-courts.ts
 */

import { initFirestore, COLLECTIONS } from '../src/db/firestore.js';
import { v4 as uuidv4 } from 'uuid';

const courts = [
  {
    name: "Ada Mckenzie Park",
    address: "185 South Park Road",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8618,
    longitude: -79.2552,
  },
  {
    name: "Armadale Park",
    address: "2401 Denison Street",
    location: "Armadale Tennis Club",
    totalCourts: 4,
    hasLights: true,
    hours: "",
    status: "CLOSED",
    latitude: 43.8978,
    longitude: -79.2415,
  },
  {
    name: "Bayview Glen Park",
    address: "48 Limcombe Drive",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8672,
    longitude: -79.3672,
  },
  {
    name: "Bayview Reservoir",
    address: "8079 Bayview Avenue",
    location: "Public",
    totalCourts: 3,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7915,
    longitude: -79.3148,
  },
  {
    name: "Berzcy Park North",
    address: "447 The Bridle Walk",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8056,
    longitude: -79.3489,
  },
  {
    name: "Berzcy Park South",
    address: "432 Wilfred Murison Avenue",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8023,
    longitude: -79.3501,
  },
  {
    name: "Blowden Davies Park",
    address: "335 Donald Cousens Parkway",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7865,
    longitude: -79.3389,
  },
  {
    name: "Boxgrove Community Park",
    address: "346 Boxgrove Bypass",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "Saturday and Sunday 12 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.7734,
    longitude: -79.3101,
  },
  {
    name: "Carlton Park",
    address: "101 Carlton Road",
    location: "Unionville Tennis Club",
    totalCourts: 9,
    hasLights: true,
    hours: "Courts 1,2,3 & 4: Tuesdays 12pm - 4pm, Courts 1 & 2: Saturdays 6pm - 10pm",
    status: "CLOSED",
    latitude: 43.9062,
    longitude: -79.2856,
  },
  {
    name: "Duncan Park",
    address: "265 Bayview Fairways Drive",
    location: "Public",
    totalCourts: 3,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8591,
    longitude: -79.3412,
  },
  {
    name: "Frisby Park",
    address: "15 Murison Drive",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8123,
    longitude: -79.3298,
  },
  {
    name: "Cornell Community Park",
    address: "371 Cornell Centre Blvd.",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.7765,
    longitude: -79.2987,
  },
  {
    name: "German Mills Park",
    address: "15 Simonston Boulevard",
    location: "German Mills Tennis Club",
    totalCourts: 4,
    hasLights: true,
    hours: "Courts 1, 2: Fridays 6 PM to 8 PM, Saturdays 2 PM to 4 PM, Sundays 4 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.8543,
    longitude: -79.3567,
  },
  {
    name: "Grandview Park",
    address: "135 Doncastor Avenue",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8489,
    longitude: -79.3298,
  },
  {
    name: "Henry White Park",
    address: "135 Moss Creek Boulevard",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7AM to Dark",
    status: "CLOSED",
    latitude: 43.7923,
    longitude: -79.2845,
  },
  {
    name: "Highgate Park",
    address: "37 Highgate Drive",
    location: "Highgate Tennis Club",
    totalCourts: 3,
    hasLights: true,
    hours: "Sundays 9 PM to 11 PM, Mondays 9 PM to 11 PM, Wednesdays 7 AM to 9 AM",
    status: "CLOSED",
    latitude: 43.8298,
    longitude: -79.3678,
  },
  {
    name: "Johnsview Park",
    address: "27 Porterfield Crescent",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8178,
    longitude: -79.3578,
  },
  {
    name: "Laura & Alf Weaver Park",
    address: "190 Williamson Road",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8834,
    longitude: -79.2567,
  },
  {
    name: "Morgan Park",
    address: "11 Parkway Avenue",
    location: "Public",
    totalCourts: 2,
    hasLights: true,
    hours: "7 AM to 11 PM",
    status: "CLOSED",
    latitude: 43.8323,
    longitude: -79.3423,
  },
  {
    name: "Pomona Mills Park",
    address: "200 John Street",
    location: "Pomona Valley Tennis Club",
    totalCourts: 6,
    hasLights: true,
    hours: "Courts 5, 6: Saturday and Sunday 12 PM to 6 PM",
    status: "CLOSED",
    latitude: 43.9012,
    longitude: -79.2678,
  },
  {
    name: "Roy Ramer Park",
    address: "11 James Parrot Ave.",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7989,
    longitude: -79.3234,
  },
  {
    name: "Reesor Park",
    address: "73 Wootten Way North",
    location: "Markham Tennis Club",
    totalCourts: 6,
    hasLights: true,
    hours: "Courts 4,5 and 6: Saturday & Sunday 3 PM to 7 PM",
    status: "CLOSED",
    latitude: 43.7623,
    longitude: -79.2845,
  },
  {
    name: "Robinson Park",
    address: "46 Robinson Street",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8789,
    longitude: -79.2789,
  },
  {
    name: "Schoolhouse Park",
    address: "7651 Ninth Line",
    location: "Boxgrove Tennis Club",
    totalCourts: 2,
    hasLights: true,
    hours: "Saturday and Sunday 12 PM to 8 PM",
    status: "CLOSED",
    latitude: 43.7689,
    longitude: -79.3156,
  },
  {
    name: "South Unionville Park",
    address: "514 Caboto Trail",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.8856,
    longitude: -79.2898,
  },
  {
    name: "Toogood Park",
    address: "58 Sciberras Road",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7567,
    longitude: -79.2934,
  },
  {
    name: "Wismer Park",
    address: "980 Bur Oak Avenue",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7923,
    longitude: -79.3012,
  },
  {
    name: "Warden View Park",
    address: "30 Rouge Valley Drive",
    location: "Public",
    totalCourts: 2,
    hasLights: false,
    hours: "7 AM to Dark",
    status: "CLOSED",
    latitude: 43.7845,
    longitude: -79.2678,
  },
];

async function seedCourts() {
  console.log('Initializing Firestore...');
  const db = initFirestore();
  
  console.log(`Seeding ${courts.length} courts...`);
  
  const batch = db.batch();
  
  for (const court of courts) {
    const docRef = db.collection(COLLECTIONS.COURTS).doc(uuidv4());
    batch.set(docRef, {
      ...court,
      courtType: "tennis",
      surface: "hard",
      isFree: court.location === "Public",
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }
  
  await batch.commit();
  console.log(`Successfully seeded ${courts.length} courts to Firestore!`);
}

seedCourts().catch(console.error);