name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - run: echo "Testing workflow"